<?php

/**
 * @file
 * Simple custom module for when someone passes a quiz.
 */

/**
 * Implements hook_quiz_finished().
 *
 * This hook function checks to see whether the quiz has been passed, and sends
 * the results to the appropriate battalion adjutant.
 *
 * @param <object> $quiz
 *   The quiz that was just taken.
 * @param array $score
 *   test score.
 * @param array $rid
 *   Results id for the test.
 */
function quiz_passed_quiz_finished($quiz, $score, $rid) {
  // dpm($quiz, 'quiz');
  // dpm($score, 'score');
  // dpm($rid, 'rid');
  if ($score['passing'] == TRUE) {
    drupal_set_message("You passed!  Well done.  We recommend you print out a copy to bring to your battalion adjutant.");
    $module = 'quiz_passed';
    $key = 'dummy_key';
    $language = language_default();
    global $user;
    
    if ($user->uid > 0) {
      $uarray = user_load($user->uid);
      $uname = $uarray->field_name['und'][0]['safe_value'];
      $ubatt = $uarray->field_battalion['und'][0]['tid'];
      $term = taxonomy_term_load($ubatt);
      $mail = $term->field_email['und'][0]['safe_value'];
      $params = array(
        '@user'       => $uarray->field_name['und'][0]['safe_value'],
        '@url'        => url('node/' . $node->nid, array('absolute' => TRUE)),
        '@quiz'       => $quiz->title,
        '@score'      => $score['percentage_score'],
        '@battalion'  => $uarray->field_battalion['und'][0]['tid'],
        '@link'       => 'http://acwa.org/node/' . $quiz->nid . '/results',
      );
      drupal_mail($module, $key, $mail, $language, $params);
    }
    
    drupal_set_message("<a href='/printquiz/" . $rid['result_id'] . "'>Print a copy</a>");
  } else {
    drupal_set_message("Sorry, you didn't pass.  Please try again.");
  }
}

/**
 * Implements hook_mail().
 */
function quiz_passed_mail($key, &$message, $params) {
  $message['subject'] = t("ACWA test results");
  $message['body'] = array();
  $message['body'][] = t("This is official notice that @user has passed the @quiz with a score of @score%.  For all results: @link", $params);
}